package ee.ttu.thesis.domain;

public enum IncomeStatementType {
    MÜÜGITULU,
    MUUD_ÄRITULUD,
    PÕLLUMAJANDUSLIKU_TOODANGU_VARUDE_JÄÄKIDE_MUUTUS,
    KASUM_KAHJUM_BIOLOOGILISTELT_VARADELT,
    VALMIS_JA_LÕPETAMATA_TOODANGU_VARUDE_JÄÄKIDE_MUUTUS,
    KAPITALISEERITUD_VÄLJAMINEKUD_OMA_TARBEKS_PÕHIVARADE_VALMISTAMISEL,
    KAUBAD_TOORE_MATERJAL_JA_TEENUSED,
    MITMESUGUSED_TEGEVUSKULUD,

    //tööjõukulud
    PÕHIVARADE_KULUM_JA_VÄÄRTUSE_LANGUS,
    OLULISED_KÄIBEVARA_ALLAHINDLUSED,
    MUUD_ÄRIKULUD,

    //kokku ärikasum-kahjum
    KASUM_KAHJUM_TÜTARETTEVÕTJATELT,
    KASUM_KAHJUM_SIDUSETTEVÕTJATELT,
    KASUM_KAHJUM_FINANTSINVESTEERINGUTELT,
    INTRESSITULUD,
    INTRESSIKULUD,
    MUUD_FINANTSTULUD_JA_KULUD,

    //Kasum (kahjum) enne tulumaksustamist
    TULUMAKS,

    //Aruandeaasta kasum (kahjum)
    EMAETTEVÕTJA_AKTSIONÄRIDE_VÕI_OSANIKE_OSA_KASUMIST,
    VÄHEMUSOSALUSE_OSA_KASUMIST
}
